# Generated by Django 4.2.2 on 2026-02-18 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miembros', '0001_initial'),
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistentes', to='actividades.actividad')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='miembros.miembro')),
            ],
            options={
                'unique_together': {('miembro', 'actividad')},
            },
        ),
    ]
