# Generated by Django 4.2.2 on 2026-02-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0001_initial'),
        ('actividades', '0001_initial'),
        ('asistencias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assistencia',
            new_name='Asistencia',
        ),
    ]
