# Generated by Django 4.2.2 on 2026-02-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiesta',
            name='fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fiesta',
            name='inicio',
            field=models.DateField(),
        ),
    ]
