# Generated by Django 4.2.2 on 2026-02-18 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0002_alter_fiesta_fin_alter_fiesta_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiesta',
            name='actividad',
        ),
    ]
