# Generated by Django 4.2.2 on 2026-02-18 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiestas', '0003_remove_fiesta_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('duracion', models.IntegerField()),
                ('fiesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='fiestas.fiesta')),
            ],
        ),
    ]
