# Generated by Django 4.2.2 on 2026-02-23 09:52

from django.db import migrations, models
import django.db.models.deletion
import miembros.models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('identificacion', 'Identificación/DNI'), ('contrato', 'Contrato Laboral'), ('titulo', 'Título Académico'), ('otros', 'Otros')], default='otros', max_length=50, verbose_name='Tipo de documento')),
                ('documento', models.FileField(blank=True, null=True, upload_to=miembros.models.ruta_documentos_miembro, verbose_name='Archivo')),
                ('nombre_documento', models.CharField(blank=True, max_length=100, verbose_name='Nombre descriptivo')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='miembros.miembro', verbose_name='Miembro')),
            ],
            options={
                'verbose_name': 'Documento de miembro',
                'verbose_name_plural': 'Documentos de miembros',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
