# Generated by Django 4.2.2 on 2026-03-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0002_miembrodocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='dni',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
