# Generated by Django 4.2.2 on 2026-03-04 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0003_miembro_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='miembro',
            name='pagador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembros_a_cargo', to='miembros.miembro', verbose_name='Responsable del pago'),
        ),
    ]
