# Generated by Django 3.1.7 on 2021-03-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idiomas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_column='codigo_idioma', help_text='Codigo vat del pais ES,DE,GB', max_length=10, verbose_name='codigo_idioma')),
                ('nombre', models.CharField(db_column='nombre', help_text='Nombre del pais', max_length=100, verbose_name='idioma')),
            ],
            options={
                'verbose_name': 'idioma',
                'verbose_name_plural': 'idioma',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Traducciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(help_text='Tabla a la que se hace referencia', max_length=100)),
                ('columna', models.CharField(help_text='Campo de la tabla al que se hace referencia', max_length=100)),
                ('columna_id', models.IntegerField(help_text='Id del registro a traducir')),
                ('idioma', models.CharField(help_text='Idioma de la traducción (es,en)', max_length=5)),
                ('traduccion', models.CharField(help_text='Texto traducido', max_length=2000)),
            ],
            options={
                'verbose_name': 'traduccion',
                'verbose_name_plural': 'traducciones',
                'ordering': ('tabla', 'columna_id'),
                'unique_together': {('columna_id', 'tabla', 'columna', 'idioma')},
                'index_together': {('columna_id', 'tabla', 'columna')},
            },
        ),
    ]
