# Generated by Django 4.2.2 on 2025-02-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idiomas',
            name='codigo',
            field=models.CharField(db_column='codigo_idioma', help_text='Codigo vat del pais ES,DE,GB', max_length=10, unique=True, verbose_name='codigo_idioma'),
        ),
    ]
